services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    network_mode: "host"
  cluster:
    build:
      context: .
      dockerfile: cluster/Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: "host"

  gameserver:
    build:
      context: .
      dockerfile: game_server/Dockerfile
    profiles: ["gameserver"]